import LiveMarket from "@/components/LiveMarket";
import LiveOrderBook from "@/components/LiveOrderBook";
import WalletButton from "@/components/WalletButton";

function Header(){return <header className="header"><div className="brand"><span className="mark">H</span><span>HOODBTC</span></div><nav><a className="active">Trade</a><a>Markets</a><a>Portfolio</a><a>Leaderboard</a></nav><div className="headerActions"><span className="status"><i/> Network live</span><WalletButton/></div></header>}
function Chart(){return <section className="panel chartPanel"><div className="panelHead"><div><button className="tab active">Chart</button><button className="tab">Info</button></div><div className="tools">1m&nbsp;&nbsp; 5m&nbsp;&nbsp; <b>15m</b>&nbsp;&nbsp; 1h&nbsp;&nbsp; 4h&nbsp;&nbsp; 1D</div></div><div className="chartMeta"><span>Chart integration next</span><span className="positive">Market header is connected to Orderly</span></div><div className="chart"><div className="bookEmpty">Live candlestick chart is not connected yet. No synthetic price line is shown.</div></div></section>}
function OrderForm(){return <aside className="panel orderPanel"><div className="orderTabs"><button className="active">Market</button><button>Limit</button><button>Advanced</button></div><div className="sideSwitch"><button className="long active">Long</button><button className="short">Short</button></div><div className="balance"><span>Available</span><b>— USDC</b></div><label className="fieldLabel">Order size</label><div className="input"><span>0.00</span><b>ETH</b></div><div className="slider"><span/><i/><i/><i/><i/></div><div className="percent"><span>0%</span><span>25%</span><span>50%</span><span>75%</span><span>100%</span></div><div className="setting"><span>Leverage</span><button>—</button></div><div className="setting"><span>Margin mode</span><button>—</button></div><label className="check"><input type="checkbox"/> Take profit / Stop loss</label><WalletButton/><div className="summary"><div><span>Est. liquidation</span><b>—</b></div><div><span>Trading fee</span><b>—</b></div><div><span>Order value</span><b>—</b></div></div><p className="noncustodial">Non-custodial execution · You control your wallet</p></aside>}
function Bottom(){return <section className="panel bottom"><div className="bottomTabs"><button className="active">Positions <em>0</em></button><button>Open orders <em>0</em></button><button>Order history</button><button>Trade history</button><button>Funding</button></div><div className="empty"><div>◎</div><b>No account data loaded</b><span>Connect a wallet to load account trading data.</span></div></section>}
export default function Home(){return <main><Header/><LiveMarket/><div className="terminal"><div className="workspace"><div className="upper"><Chart/><LiveOrderBook/></div><Bottom/></div><OrderForm/></div><footer><span>HOODBTC</span><span>Decentralized trading interface</span><span className="positive">● Orderly market data</span></footer></main>}
